# Generated by Django 4.2.18 on 2025-02-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('selling_price', models.FloatField()),
                ('maximum_reatil_price', models.FloatField()),
                ('flavour', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=100)),
                ('Images', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
