# Generated by Django 4.2.18 on 2025-02-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='ingredients',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
