# Generated by Django 4.2.18 on 2025-02-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0002_alter_addproduct_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='Images',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='ingredients',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
