# Generated by Django 4.2.18 on 2025-02-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0003_remove_addproduct_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='maximum_reatil_price',
            new_name='maximum_retail_price',
        ),
        migrations.RenameField(
            model_name='addproduct',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='ingredients',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
