# Generated by Django 4.2.18 on 2025-02-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppModel', '0004_rename_maximum_reatil_price_addproduct_maximum_retail_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='images',
        ),
    ]
